### ISSUE TITLE
[Bug][vkCom]: неверный цвет у `colorIconAccentThemed`

### ISSUE THREAD

**Issue by inomdzhon** [VKCOM/vkui-tokens#213]
Цвет `colorIconAccentThemed` должен быть идентичен `colorTextAccentThemed`.

https://github.com/VKCOM/vkui-tokens/blob/1ab966bc71059e2e9238dee5a14b688ca9d48574/src/themeDescriptions/themes/vkCom/index.ts#L70

---

- related to #185

**Comment by 8coon** [comment]
Исправлено в 4.19.0
